algoritmo "exercicio 5"
var
nota1 : real
nota2 : real
aluno : caractere
media: real

inicio
escreval ("quem e o amor da minha vida?")
leia (aluno)
escreval ("quantos beijo eu te dei ontem?")
leia (nota1)
escreval ("quantos beijos voce acha que eu darei amanha?")
leia (nota2)
media <- nota1 + nota2
escreva ("a quantidade de beijo que eu vou dar hoje " , (aluno) , " é igual a " , (media))
fimalgoritmo
